name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: yarn lint

  test:
    runs-on: ubuntu-latest
    env:
      DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: yarn --frozen-lockfile
      - run: yarn test
