name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: yarn
      - run: yarn build
      - run: yarn lint

  test:
    runs-on: ubuntu-latest
    env:
      BASIC_API_KEY: ${{ secrets.BASIC_API_KEY }}
      PLUS_API_KEY: ${{ secrets.PLUS_API_KEY }}
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: yarn
      - run: yarn test
